### ISSUE TITLE
Add a docker container

### ISSUE THREAD

**Issue by simplyboo6** [simplyboo6/Vimtur#13]

**Comment by simplyboo6** [comment]
I'm not familiar with Docker and can't figure out a good way to be able to save a config outside of the docker container or access the library on the host machine

**Comment by sparky8251** [comment]
Saving the config outside the container can be a bit of a pain depending on the projects current structure.

Whats the default path the program and its files install at and whats the default path the config saves at?

Accessing the hosts library should be a rather simple task comparatively.

**Comment by simplyboo6** [comment]
The program doesn't really install anywhere, just run it (if I understand your question). The config by default is config.json in the current working directory. It's location can be specified in the command line. The config.json also contains the path to the sqlite3 database if applicable and the user can specify any location for it.

**Comment by sparky8251** [comment]
Shouldn't be too hard to make a dockerfile for it then.

Over the next two weeks I'm moving so I might not have time, but I'll give it a go. Got a place we can chat so I can work out some implementation details?

Already did this for another young project :)

**Comment by simplyboo6** [comment]
Sure, simplyboo6@gmail.com

**Comment by turbomettwurst** [comment]
i just tried creating one, the usual problem of storing secrets pops up.

While i could simply create some laucher script das rewrites config.json based on env vars or docker secrets whenever the container starts, it would be much nicer if vimtur could simply use that information directly so we can discard the config file entirely.

**Comment by simplyboo6** [comment]
I could move everything except the database configuration to the database but I'm not convinced that's a great solution. Are you sure you couldn't just mount the folder the config.json is in and point the application at that?

**Comment by sparky8251** [comment]
@simplyboo6 The issue with that is how docker mounts stuff. It layers the folder outside the container inside of it. You can't provide a single file, it MUST be a directory if its to live outside the container. This means that if I make a file (outside the container)

/data/Vimtur/conf/config.json

and try to mount it inside the container at

/app/programroot/config.json

I must mount

/data/Vimtur/conf at /app/programroot

and now /app/programroot ONLY contains config.json.

Two easy options I can see (might introduce later issues depending on how you develop the program):

1) Provide a file like vars.json that allows us to specify a different dir for the config.json. With this we can place the conf files where ever we want at the time we build the container.

2) Move the config.json to its own subfolder like $programroot/config/config.json. This allows us to override the entire config folder but requires that your program can generate required default config files on first run (or the user must supply them).

**Comment by turbomettwurst** [comment]
You don't have to explicitly move it, just check for env vars and fallback to config if needed.
Any reason db credentials need to be pulled from a config file?
While moving configuration data to volumes is fine for single host installations, it can create a severe penalty if volumes are network attached storage.
The cleanest way would be using docker secrets, but this will make it somewhat complicated for beginners.
Second best option is env vars used by the application itself, as pretty much any docker frontend in existence has support for setting them easily.
Third best Option is setting them in env vars, and use docker-entrypoint.sh to sed the env vars in to the configuration file before starting the actual application.

**Comment by simplyboo6** [comment]
@sparky8251 The location of config.json can be specified as an argument, it's always the last argument and must be called config.json.
Eg npm run server ./conf/config.json
If it doesn't exist then the config page will write to that file.

I tend to prefer specifying passwords in config files rather than at command line, otherwise it'll end up in logs. That's only really relevant if the user is using MySQL though.

**Comment by simplyboo6** [comment]
I've added Docker support. Feel free to re-open this issue if there's anything that could be done better.
