### ISSUE TITLE
index.js error when starting server

### ISSUE THREAD

**Issue by dashbad** [simplyboo6/Vimtur#16]
Debian 9.6
node 6.15.1
npm 3.10.10
debug log attached.

I am trying to run natively. npm install executes fine. When I run npm run server I get:

/opt/Vimtur-release-3.2.1/index.js:17
const configCheckConnector = async function (req, res, next) {
                                   ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
npm ERR! node v6.15.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Vimtur@3.2.0 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Vimtur@3.2.0 server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Vimtur package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Vimtur
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Vimtur
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/Vimtur-release-3.2.1/npm-debug.log
[npm-debug.log](https://github.com/simplyboo6/Vimtur/files/2656210/npm-debug.log)

**Comment by simplyboo6** [comment]
Hi Dashbad, to run this you need at least NodeJS V8.
