### ISSUE TITLE
Adaptive Bitrate ?

### ISSUE THREAD

**Issue by UnR34L** [simplyboo6/Vimtur#17]
Would it be possible to add an adaptive bitrate feature similar to: https://hub.docker.com/r/majamee/alpine-dash-hls

I tried this and I was amazed at how good it was.

**Comment by simplyboo6** [comment]
Hi, I've implemented this in the vimtur-4 branch. It can now be configured to transcode to whatever bitrates are specified.

If you'd like to use it before I release it I'd love to get some feedback.
Checkout the vimtur-4 branch here: https://github.com/simplyboo6/Vimtur/tree/vimtur-4
Also have a look at the config section for configuring the bitrates you'd like to use, by default it transcodes to 240p and 1080p

**Comment by simplyboo6** [comment]
I'm now happy enough with the upgrade path that I've released 4.0 :)

**Comment by UnR34L** [comment]
Works great, thanks for adding this :D 

Should it be working with 3 tiers ?

I put the config.json in the cache directory
```
{
  "port": 3523,
  "transcoder": {
    "maxCopyEnabled": true,
    "minQuality": 480,
    "qualities": [
      240,
      720,
      1080
    ]
  },

```
(omitted the rest of the config)


but I'm only getting 240p and 1080p (used a 1080p video for testing)

**Comment by simplyboo6** [comment]
Should be working, I'll give it a test

**Comment by UnR34L** [comment]
oh it's not reading the config file for some reason, tested it by changing the port and the logs still say it's listening on 3523.

So maybe it does work with three tiers.

**Comment by simplyboo6** [comment]
You're right for sure. It's missing a "-c" in the Dockerfile, when I added it though there were duplicate items in the qualities array so I'm just resolving that then I'll push the fix up

**Comment by simplyboo6** [comment]
Pushed up, give that a try

**Comment by UnR34L** [comment]
I had to add this to mongo and set the user and password in config.json before it would connect
```
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
```
I thought if it was linked it wouldn't need that?

A few odd things, doesn't look like it''s using HLS now, there's only one index.ts in each folder. When I only set, 720 and 1080 it still produces a 240p + the others.

anyway, does what I wanted, thanks!

**Comment by simplyboo6** [comment]
That's strange, running locally I've not reproduced the Mongo issue. By default there shouldn't be a username/password I wonder if I'm using a cached copy.

There should be an index.m3u8 containing a list of available copies and then the specific qualities are under folders eg {hash}/720p/index.m3u8 etc :)
