### ISSUE TITLE
Software is amazing - two suggestions 

### ISSUE THREAD

**Issue by commander-flatus** [simplyboo6/Vimtur#23]
Can you make it so metadata pops up to the left of the media like the tagging screen does?

Also, mass tagging based on file name or directory name would be an incredible feature as well. 

Thanks for the hard work. I’d be delighted to contribute financially to the project if you tell me how.

**Comment by simplyboo6** [comment]
Hi @commander-flatus sorry for missing this issue. The first requests easy enough so you'll see it soon now I've noticed it.

The latter may be tricky if it gets too complex. Would applying the bulk update to whatever the current search result is work for you? (It's possibly already to view every file in the same folder [not nested though]), or search by keyword which includes path. Do you also want to be able to explicitly search for something like the path includes an exact string?

**Comment by simplyboo6** [comment]
Artist/Album/Title should now be available in the quick-tag panel. There's settings to disable individual component under Config.

**Comment by commander-flatus** [comment]
Thanks for the updates. Is there a way to support this project financially?
Also - an option to display the full filename and path in the tagging sidebar would be super.

**Comment by simplyboo6** [comment]
Not at the moment. I've applied for Github sponsors. I've just added the path and filename of the media overlayed at the top of the media.

**Comment by simplyboo6** [comment]
I've implemented applying artist/album/title to all current search results (with a confirmation modal). Are there any other fields that you can think of a use-case for bulk updating?

**Comment by commander-flatus** [comment]
More suggestions incoming:
- I was hoping to get the filename and directory to be able to appear somewhere in the tagging window or the viewer (above or below) - this would speed up tagging instead of going between the media viewer and the metadata "tab"/"screen"
- Search by media length for video files?

**Comment by simplyboo6** [comment]
The first ones implemented, see this screenshot for example https://raw.githubusercontent.com/simplyboo6/Vimtur/master/screenshots/viewer.png

Paths are all relative to DATA_DIR. The visibility of it can be toggled on the config page along with a few other widgets in the viewer.

Coincidentally I had the same thought with searching. It was lacking a few bits searching by length, filtering by actors, filtering by path, sorting by length etc. The redesigned options are in this screenshot: https://raw.githubusercontent.com/simplyboo6/Vimtur/master/screenshots/search.png

**Comment by commander-flatus** [comment]
For some reason the filename and path doesn't show up for me. I'm on a Mac - latest OS - tried Chrome, Safari, and Firefox.

**Comment by simplyboo6** [comment]
That's really damn weird. I did a quick test on Chrome Windows/Linux and Firefox Windows/Linux but can't reproduce. Best I think we can do is a sanity check. Are you definitely running the latest version? If from source have you definitely rebuilt? If yes (which is probably the case if you're looking at search) then in the config is `Show path above media?` checked?

I'm glad you like it. I'm always happy to hear suggestions irrespective of donations.

**Comment by commander-flatus** [comment]
I deleted the docker and re-ran the compose with your suggested docker-compose.yml file. I don't see the option listed in config......

Maybe I'm missing something but I thought when I deleted the docker and re-ran the compose it would pull the latest version.

**Comment by simplyboo6** [comment]
I'm not sure whether you cloned the repository or if you're using the image from Docker hub.

If you cloned the repository:
```
git pull origin master
docker-compose up --build
```

If you're using the Docker hub image (eg your compose file contains "image: simplyboo6/vimtur:4" [I recommend 4 over latest for stability when I'm adding new features]):
```
docker-compose pull
docker-compose up
```

**Comment by simplyboo6** [comment]
Did the above resolve your issue?
My Github sponsor account has been approved if you'd still like to donate. https://github.com/sponsors/simplyboo6

**Comment by commander-flatus** [comment]
yes it did! sponsored!
My only ongoing issue is that I now cannot add actors from the viewing screen like before.
Keep up the excellent work!

**Comment by simplyboo6** [comment]
Thanks for the sponsorship! :)
Is `Show people?` checked under Config ->UI Configuration -> Quick Tag Panel Configuration?

**Comment by commander-flatus** [comment]
Yes, it is. I may not be on the latest and greatest version though because I’m having it generate previews and thumbnails for a whole pile of videos and I don’t want to update ATM.
