### ISSUE TITLE
Add support for collections/playlists

### ISSUE THREAD

**Issue by simplyboo6** [simplyboo6/Vimtur#3]

**Comment by simplyboo6** [comment]
Server-side now implemented

**Comment by simplyboo6** [comment]
I'm unsure how to best do this in the UI, and other than an explicit order I don't think it adds anything over tagging. For now I'm going to delay this issue until I have some better ideas for the UI.

**Comment by simplyboo6** [comment]
Marked as help wanted for UI suggestions mostly

**Comment by Kesslerb2** [comment]
Finally found a use case for this. If you have a comic collection imported you're not guaranteed order. Playlist functionality would allow you to set their order. 

From a UI point of view, it would be interesting to be able to filter by playlists (Just like gif/still/video) or just have a playlist tab. Each playlist would show up as one element in the gallery and on selection, would expand to show the files inside the playlist in their set order.

**Comment by simplyboo6** [comment]
Thanks. That's given me a good direction to go in. It does raise other questions such as whether a playlist should have metadata attached to it the same way as media does. I think in the short-term probably not.

Where I've also struggled with this is how media should be added and removed from a playlists. Perhaps a tag input box the same as the "People" input?

To help with your sorting problem though there's a few sort by options in the search tab. You may find sorting by path or creation date will help.

**Comment by Kesslerb2** [comment]
I've thought about work arounds using the existing sort settings. Unfortunately I save my files using the phash as the file name to avoid duplicates.

I think adding would work just like the tag input box. You would have a drop-down of existing playlists (just like tags) and if you wanted to create a new playlist you could just ignore the drop-down contents and type out the full name. It would auto be added to the end of the playlist but some sort drag mechanism inside the playlist view would allow you to reorder it. Similar to how YouTube does playlists.

**Comment by Kesslerb2** [comment]
I think for meta-data to start you would just need the Playlist name and contents in a collection. If you wanted to show artists/authors/tags/ect. in the playlist you could do a Mongo query on the contents of the playlist and create a set from their meta data.

**Comment by simplyboo6** [comment]
Most of the back-end is now done (even with automated tests). Still outstanding is an API to add to a playlist based on search criteria. It should when complete be possible to search within playlists although I'm not sure how that would work with re-ordering, it may have to be read-only when viewing a subset of a playlist.

**Comment by simplyboo6** [comment]
The core of the front-end is done now. It's possible to create or delete playlists, add the current search set to a playlist, re-order and remove an item from a playlists.

The last thing left to do is add the multi-select to the viewer and metadata tabs for adding and removing an item from a playlist. It turns out to be quite complicated when you already have a playlist selected.

**Comment by simplyboo6** [comment]
An update since this has been going on for a while. It's mostly implemented on a pushed up branch now excluding managing playlists from the metadata tab, but it can be done from the tag panel. I've run into many interesting performance issues when creating this but there's one last one that's very difficult to debug. If I select a playlist then switch to the viewer and back to the playlist the CPU usage goes to 100% for about 5 minutes and then back down again. Suffice to say it's a bit of a fatal bug and I can't release it until it's solved.

**Comment by simplyboo6** [comment]
Finally came back to this with a clean set of eyes. It was a couple of different problems that only now have become exposed.

The HTML in the tag panel had a lovely render loop because in my earlier Angular days I'd called a function to build an array so the change detector would be constantly triggered.

The latter problem, and I'm not sure of the cause, was the resize sensor on the video player. I've removed that library and now use the browsers ResizeObserver with a polyfill.

**Comment by simplyboo6** [comment]
Now all done, merged and released as version 5
