### ISSUE TITLE
Configurable Number of Items Per Page

### ISSUE THREAD

**Issue by Kesslerb2** [simplyboo6/Vimtur#31]
This is a feature request to have a config option to set the number of items displayed per page. If set to 0 or greater than the query count, it would show all items that matched the query on a single page. If less than the query count, it would show that many items per page and enable the next/previous page buttons.

**Comment by simplyboo6** [comment]
Welcome :) This sounds great, I'll add it to the next patch release with a couple of other enhancements.

**Comment by simplyboo6** [comment]
Now resolved on master. I'll release in the next few days once I'm sure nothing's broken. If you'd like it sooner you can switch to the latest Docker tag :)
