### ISSUE TITLE
Header should anchor

### ISSUE THREAD

**Issue by Kesslerb2** [simplyboo6/Vimtur#34]
This is a feature request.

The header bar/navigation bar should be an anchored element. This way when you scroll to the bottom you can still go to the next page without having to scroll to the top to get to the next set of entries.

**Comment by simplyboo6** [comment]
17 days for me to notice this! Sorry @Kesslerb2 

I'll see what I can do, I had some issues initially getting the content to fill the screen without being under the pinned navbar but I have some thoughts on how to work around that.

**Comment by simplyboo6** [comment]
Resolved on master, and latest after the build finishes. This will be included in 4.7.0.
