### ISSUE TITLE
issues with getting program running

### ISSUE THREAD

**Issue by skier233** [simplyboo6/Vimtur#45]
I'm having issues getting the program working. The command listed in the docs doesn't actually work in windows. I can get the webapp running but it doesnt seem to see any files in the volume. Furthermore, eventually I'm going to need to point it to a folder on a separate drive.

**Comment by simplyboo6** [comment]
I haven't tried to run it on Windows and if you get past that stage you'll likely run into issues with ffmpeg and some other binaries not being found.
It's possible to run Linux Docker containers on Windows if you follow these steps. https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers
